### PR TITLE
mcp: update JSON marshaling to not HTML-escape messages

### LINKED ISSUE #238: Idea: environment variable for experiments and compatibility
Once this module is at v1, we won't make any breaking API changes. But we may make slight behavior changes. For example, our streaming transport implementation may return more fine-grained HTTP status codes to help clients distinguish different types of errors, or we might turn some code paths that are currently successful into errors if they violate the specification or they inevitably lead to errors further on. We want to give users time to adapt their implementation to these changes.

We also may conduct experiments, adding new features that we're not sure are the right ones, or have the right API. We want to allow users to opt in to these experiments.

We propose to provide for both of these cases with an environment variable, GOMCPSDK. Its value will be a comma-separated list of key=value pairs. Each entry will either restore old behavior or enable an experiment.

The README for the module will document the each entry and, for compatibility-preserving entries, when they will expire. A typical compatibility entry will expire after one minor version has passed, locking in the new behavior. For example, an entry introduced in v1.3 will be removed in v1.5.

### LINKED ISSUE #767: StreamableHTTP transport timeout issue.
**Describe the bug**
The Go MCP SDK client experiences a 60-second timeout (504 Gateway Timeout) when calling tools on the remote MCP server at mcp.on-demand.io, while the Node.js MCP SDK client successfully completes the same request in ~1 second. The issue appears to be a server-side compatibility problem with how the Go SDK's requests are processed.

**To Reproduce**
1. Install the official Go MCP SDK:
```
go get github.com/modelcontextprotocol/go-sdk/mcp
```
2. Create a Go client connecting to the remote MCP server:
```
   client := mcp.NewClient(&mcp.Implementation{
       Name:    "mcp-mermaid-client",
       Version: "1.0.0",
   }, nil)
   transport := &mcp.StreamableClientTransport{
       Endpoint:   "https://mcp.on-demand.io/instances/presight-mermaid-mcp/mcp?apiKey=<REDACTED>",
       HTTPClient: &http.Client{Timeout: 0},
       MaxRetries: 3,
   }
   session, err := client.Connect(ctx, transport, nil)
```
3. Call the generate_mermaid_diagram tool:
```
   params := &mcp.CallToolParams{
       Name: "generate_mermaid_diagram",
       Arguments: map[string]any{
           "mermaid": "graph TD\n    A-->B",
           "outputType": "mermaid",
       },
   }
   
   result, err := session.CallTool(ctx, params)
```

**Expected behavior**
The Go client should successfully call the generate_mermaid_diagram tool and receive the mermaid diagram response within a reasonable time (~1-2 seconds), similar to the Node.js client behavior.

**Logs**
```
2026/01/28 12:50:42 Calling generate_mermaid_diagram tool...
2026/01/28 12:50:42 Starting tool call...
2026/01/28 12:50:42 === HTTP REQUEST ===
POST /instances/presight-mermaid-mcp/mcp?apiKey=<REDACTED> HTTP/1.1
Host: mcp.on-demand.io
User-Agent: Go-http-client/1.1
Content-Length: 165
Accept: application/json, text/event-stream
Content-Type: application/json
Mcp-Protocol-Version: 2025-06-18
Accept-Encoding: gzip

{"jsonrpc":"2.0","id":2,"method":"tools/call","params":{"name":"generate_mermaid_diagram","arguments":{"mermaid":"graph TD\n    A--\u003eB","outputType":"mermaid"}}}

2026/01/28 12:51:42 === HTTP RESPONSE (after 1m0.316470083s) ===
HTTP/2.0 504 Gateway Timeout
Content-Length: 102
Access-Control-Allow-Origin: *
Content-Security-Policy: default-src 'none'; frame-ancestors 'none'
Content-Type: application/json; charset=utf-8
Date: Wed, 28 Jan 2026 07:21:42 GMT

2026/01/28 12:51:42 CallTool failed after 1m0.316810209s: calling "tools/call": rejected by transport: sending "tools/call": Gateway Timeout
```

### PR DESCRIPTION
**Pull request by maciej-kisiel**
It's causing some servers to fail: #767. I checked with Typescript implementation and it doesn't do any escaping.

It's still a behavior change.

Fixes #238 
Fixes #767

### CODE REVIEW

**Comment by jba** [comment]
We should provide a way to preserve the old behavior. We don't know who depends on it.
See https://github.com/modelcontextprotocol/go-sdk/issues/238.
For example code, see https://github.com/google/jsonschema-go/blob/main/jsonschema/infer.go#L138.

File: internal/jsonrpc2/messages.go [hunk 1]
```diff
@@ -158,6 +159,7 @@ func EncodeMessage(msg Message) ([]byte, error) {
 func EncodeIndent(msg Message, prefix, indent string) ([]byte, error) {
 	wire := wireCombined{VersionTag: wireVersion}
 	msg.marshal(&wire)
+	// TODO: do we need to escape HTML here?
```
Comment (jba) [inline internal/jsonrpc2/messages.go]: It's only used in tests, but why should tests behave differently? So you should turn off escaping here too.

File: internal/jsonrpc2/messages.go [hunk 2]
```diff
@@ -204,9 +206,21 @@ func marshalToRaw(obj any) (json.RawMessage, error) {
 	if obj == nil {
 		return nil, nil
 	}
-	data, err := json.Marshal(obj)
+	data, err := jsonMarshal(obj)
```
Comment (jba) [inline internal/jsonrpc2/messages.go:213]: If you grep the codebase, there are many other calls to json.Marshal. Should they all go to jsonMarshal? I'm not sure.

Comment (findleyr) [reply internal/jsonrpc2/messages.go:213]: If this is specifically about messages, this is probably the only location that needs to change.

File: internal/jsonrpc2/messages.go (hunk 1 above)
Comment (maciej-kisiel) [reply internal/jsonrpc2/messages.go]: Done

**Comment by maciej-kisiel** [comment]
Added a simple package to allow specifying compatibility flag as suggested in https://github.com/modelcontextprotocol/go-sdk/issues/238.

File: internal/mcpgodebug/mcpgodebug.go [hunk 3]
```diff
@@ -0,0 +1,52 @@
...
+
+// Value returns the value of the compatibility parameter with the given key.
+// It returns an empty string if the key is not set.
+func Value(key string) string {
+	return compatibilityParams[key]
+}
+
+func parseCompatibility(envValue string) (map[string]string, error) {
+	if envValue == "" {
+		return make(map[string]string), nil
```
Comment (jba) [inline internal/mcpgodebug/mcpgodebug.go]: return nil, nil

File: internal/mcpgodebug/mcpgodebug.go [hunk 4]
```diff
@@ -0,0 +1,52 @@
...
+	}
+
+	params := make(map[string]string)
+	for _, part := range strings.Split(envValue, ",") {
+		kv := strings.Split(part, "=")
+		if len(kv) != 2 {
+			return nil, fmt.Errorf("MCPGODEBUG: invalid format: %q", part)
+		}
+		params[kv[0]] = kv[1]
```
Comment (jba) [inline internal/mcpgodebug/mcpgodebug.go]: strings.TrimSpace for both kv's

File: internal/mcpgodebug/mcpgodebug.go [hunk 5]
```diff
@@ -0,0 +1,52 @@
...
+}
+
+func parseCompatibility(envValue string) (map[string]string, error) {
+	if envValue == "" {
+		return make(map[string]string), nil
+	}
+
+	params := make(map[string]string)
+	for _, part := range strings.Split(envValue, ",") {
+		kv := strings.Split(part, "=")
```
Comment (jba) [inline internal/mcpgodebug/mcpgodebug.go]: Better:
```
k, v, ok := strings.Cut(part, "=")
if !ok {error}
```
A bit easier to write and also allows = in value (why not?)

File: internal/mcpgodebug/mcpgodebug_test.go [hunk 6]
```diff
@@ -0,0 +1,70 @@
...
+
+package mcpgodebug
+
+import (
+	"testing"
+
+	"github.com/google/go-cmp/cmp"
+)
+
+func TestParseCompatibility_Success(t *testing.T) {
```
Comment (jba) [inline internal/mcpgodebug/mcpgodebug_test.go:13]: nit: avoid underscores in test function names. (We seem to have a couple, maybe that's Claude's fault.)

File: internal/mcpgodebug/mcpgodebug_test.go [hunk 7]
```diff
@@ -0,0 +1,70 @@
...
+	got, err := parseCompatibility("foo=bar,baz=qux")
```
Comment (jba) [inline internal/mcpgodebug/mcpgodebug_test.go]: test with spaces around some parts

File: internal/mcpgodebug/mcpgodebug.go (hunk 3 above)
Comment (maciej-kisiel) [reply internal/mcpgodebug/mcpgodebug.go]: Thanks! I thought it will panic in Value if it's `nil` but TIL that only writes panic, reads do not.

File: internal/mcpgodebug/mcpgodebug_test.go (hunk 6 above)
Comment (maciej-kisiel) [reply internal/mcpgodebug/mcpgodebug_test.go:13]: They seem to generally be allowed, even in the Google Go style which is pretty opinionated: https://google.github.io/styleguide/go/decisions#underscores. From my perspective they allow easier separation of the function under test from the testing scenario. Do you feel strongly?

Comment (jba) [reply internal/mcpgodebug/mcpgodebug_test.go:13]: You can leave them.
