### PR TITLE
mcp: set default logging level to info

### LINKED ISSUE #387: Server notifications are not sent out in stateless mode
**Describe the bug**
With https://github.com/modelcontextprotocol/go-sdk/pull/307 the `Stateless` flag was introduced. The documentation for the flag says that `Server->Client notifications may reach the client if they are made in the context of an incoming request`. However, I cannot get them to work again after the update to 0.3.0 of this library.

I explicitly set the logging level to debug in the inspector:
Image

The state update also reaches the server:
Image

But if I look at the stored `logLevel` when sending a notification, it is empty:
Image

So I think the state is not correctly handled in stateless mode. Or am I missing something?

**To Reproduce**
Minimal example:
```go
package main

import (
	"context"
	"flag"
	"log"
	"net/http"
	"os"

	"github.com/modelcontextprotocol/go-sdk/mcp"
)

var httpAddr = flag.String("http", "", "if set, use streamable HTTP at this address, instead of stdin/stdout")

func main() {
	flag.Parse()

	server := mcp.NewServer(&mcp.Implementation{Name: "everything"}, nil)

	mcp.AddTool(server, &mcp.Tool{Name: "greet", Description: "say hi"}, contentTool)

	if *httpAddr != "" {
		handler := mcp.NewStreamableHTTPHandler(
			func(*http.Request) *mcp.Server {
				return server
			}, &mcp.StreamableHTTPOptions{Stateless: true},
		)
		log.Printf("MCP handler listening at %s", *httpAddr)
		http.ListenAndServe(*httpAddr, handler)
	} else {
		t := &mcp.LoggingTransport{Transport: &mcp.StdioTransport{}, Writer: os.Stderr}
		if err := server.Run(context.Background(), t); err != nil {
			log.Printf("Server failed: %v", err)
		}
	}
}

type args struct {
	SomeString string `json:"someString" jsonschema:"A random string"`
}

func contentTool(ctx context.Context, req *mcp.CallToolRequest, args args) (*mcp.CallToolResult, any, error) {
	req.Session.Log(ctx, &mcp.LoggingMessageParams{Logger: "logger", Level: "debug", Data: "Some data"})

	return &mcp.CallToolResult{
		Content: []mcp.Content{
			&mcp.TextContent{Text: "Something"},
		},
	}, nil, nil
}
```

1. Run the code above
2. Connect to the server and set logging level to debug
3. Perform a request

**Expected behavior**
The example above should work as the notification is sent in the context of the incoming request.

### PR DESCRIPTION
**Pull request by ln-12**
During initialization, the default logging level is set to info allowing servers to emit logs immediately without waiting for a client to set a log level.
The updated example shows how to send a notification in the context of the request.

Fixes #387

### CODE REVIEW

File: examples/server/distributed/main.go [hunk 1]
```diff
@@ -144,15 +144,19 @@ func parent() {
 }
 
 func child(port string) {
-	// Create a server with a single tool that increments a counter.
-	server := mcp.NewServer(&mcp.Implementation{Name: "counter"}, nil)
+	// Create a server with a single tool that increments a counter and sends a notification.
+	opts := &mcp.ServerOptions{
```
Comment (jba) [inline examples/server/distributed/main.go]: I'd rather not introduce a new exported symbol. Let's hardcode the default level.
And let's make it Info, not Debug. Otherwise servers are likely to spam clients who don't care.
(In my experience, debug logs are often 10x the size of info logs.)

Comment (ln-12) [reply examples/server/distributed/main.go]: Alright, changed it.

**Comment by jba** [comment]
Thanks!
