### PR TITLE
mcp: cleanup transport after keepalive ping fails

### LINKED ISSUE #258: streamable session persists past client disconnect
StreamableHTTPHandler holds a map of StreamableServerTransports. Currently, an entry from that map is freed only when the client sends a DELETE. We should also free it when the client stops responding to keepalive pings. If clients don't send DELETEs, the server memory will grow without bound.

### PR DESCRIPTION
**Pull request by h9jiang**
An onClose function is passed to the ServerSession and ClientSession to help cleanup resources from the caller.

The onClose function will be executed as part of the ServerSession and ClientSession closure.

Fixes #258

### CODE REVIEW

File: mcp/streamable.go [hunk 1]
```diff
@@ -40,6 +40,8 @@ type StreamableHTTPHandler struct {
 	getServer func(*http.Request) *Server
 	opts      StreamableHTTPOptions
 
+	onTransportDeletion func(sessionID string) // for testing only
```
Comment (h9jiang) [inline mcp/streamable.go:43]: I would prefer not to add this field only for testing purpose. But the test need some signal from the production indicating `transportations` have changed. 

Let me know if you have any better solution to this.

File: mcp/streamable_test.go [hunk 2]
```diff
@@ -332,6 +333,78 @@ func testClientReplay(t *testing.T, test clientReplayTest) {
...
+			if id == nClient {
+				t.Errorf("creating more than %v session", nClient)
+			}
+			chans[fmt.Sprint(id)] = make(chan struct{}, 1)
+			return fmt.Sprint(id)
+		},
+	})
+
+	handler.onTransportDeletion = func(sessionID string) {
+		mu.Lock()
```
Comment (findleyr) [inline mcp/streamable_test.go]: There is no need to lock here: channel sends are concurrency safe.

File: mcp/transport.go [hunk 3]
```diff
@@ -122,15 +122,15 @@ func NewInMemoryTransports() (*InMemoryTransport, *InMemoryTransport) {
 }
 
 type binder[T handler, State any] interface {
-	bind(Connection, *jsonrpc2.Connection, State) T
+	bind(Connection, *jsonrpc2.Connection, State, func()) T
```
Comment (findleyr) [inline mcp/transport.go:126]: You can add `// TODO(rfindley): the bind API has gotten too complicated. Simplify.`

**Review by findleyr — COMMENTED** [review]
Thanks! This essentially LGTM, but a couple superficial comments.

File: mcp/streamable_test.go (hunk 2 above)
Comment (h9jiang) [reply mcp/streamable_test.go]: Done.

File: mcp/transport.go (hunk 3 above)
Comment (h9jiang) [reply mcp/transport.go:126]: Done.

**Review by findleyr — APPROVED** [review]
