### PR TITLE
mcp: treat pointers equivalently to non-pointers when deriving schema

### LINKED ISSUE #199: No tools are advertised when assigning a pointer type in the generic for `CallToolParamsFor`
**Describe the bug**
When the generic type for `CallToolParamsFor` is a pointer in the `ToolHandlerFor`, the tool is not included in the response to `tools/list`.

**To Reproduce**

Prove that tools are included in the response with non-pointer types:

1. Create a small server:

    ```go
    package main
    
    import (
    	"context"
    	"net/http"
    
    	"github.com/modelcontextprotocol/go-sdk/mcp"
    )
    
    func main() {
    	server := mcp.NewServer(&mcp.Implementation{Name: "hello"}, nil)
    
    	mcp.AddTool(server, &mcp.Tool{
    		Name:        "greet",
    		Description: "Say hello",
    	}, func(ctx context.Context, ss *mcp.ServerSession, params *mcp.CallToolParamsFor[struct{}]) (*mcp.CallToolResultFor[struct{}], error) {
    		return &mcp.CallToolResultFor[struct{}]{
    			Content: []mcp.Content{
    				&mcp.TextContent{Text: "hello"},
    			},
    		}, nil
    	})
    
    	http.ListenAndServe(":8080", mcp.NewStreamableHTTPHandler(func(*http.Request) *mcp.Server {
    		return server
    	}, nil))
    }
    ```

2. Start the server:

    ```shell
    go run main.go
    ```

3. List the tools:

    ```shell
    SESSION_ID=$(curl -sfo /dev/null -w '%header{mcp-session-id}' localhost:8080 \
      -H 'Accept: application/json,text/event-stream' \
      -H 'Mcp-Protocol-Version: 2025-06-18' \
      -d '{
      "jsonrpc":"2.0",
      "id":1,
      "method":"initialize",
      "params":{
        "protocolVersion":"2025-06-18",
        "capabilities":{},
        "clientInfo":{"name":"Seth", "title":"Seth Test Client", "version":"1.0.0"}
      }
    }'
    )
    ```

    ```shell
    curl -v localhost:8080 \
      -H "Accept: application/json,text/event-stream" \
      -H "Mcp-Protocol-Version: 2025-06-18" \
      -H "Mcp-Session-Id: ${SESSION_ID}" \
      -d '{
      "jsonrpc":"2.0",
      "method":"notifications/initialized"
    }'
    ```

    ```shell
    curl -v localhost:8080 \
      -H 'Accept: application/json,text/event-stream' \
      -H "Mcp-Protocol-Version: 2025-06-18" \
      -H "Mcp-Session-Id: ${SESSION_ID}" \
      -d '{
      "jsonrpc":"2.0",
      "id":1,
      "method":"tools/list",
      "params":{}
    }'
    ```

4. Get a response:

    ```text
    event: message
    id: 3_0
    data: {"jsonrpc":"2.0","id":1,"result":{"tools":[{"description":"Say hello","inputSchema":{"type":"object","additionalProperties":{"not":{}}},"name":"greet","outputSchema":{"type":"object","additionalProperties":{"not":{}}}}]}}
    ```

5. Stop the server

6. Alter the code to use a pointer in `mcp.CallToolParamsFor`:

    ```diff
    -	}, func(ctx context.Context, ss *mcp.ServerSession, params *mcp.CallToolParamsFor[struct{}]) (*mcp.CallToolResultFor[struct{}], error) {
    +	}, func(ctx context.Context, ss *mcp.ServerSession, params *mcp.CallToolParamsFor[*struct{}]) (*mcp.CallToolResultFor[struct{}], error) {
    ```

7. Start the server:

    ```shell
    go run main.go
    ```

8. Run the same commands from step 3 above:

    ```shell
    SESSION_ID=$(curl -sfo /dev/null -w '%header{mcp-session-id}' localhost:8080 \
      -H 'Accept: application/json,text/event-stream' \
      -H 'Mcp-Protocol-Version: 2025-06-18' \
      -d '{
      "jsonrpc":"2.0",
      "id":1,
      "method":"initialize",
      "params":{
        "protocolVersion":"2025-06-18",
        "capabilities":{},
        "clientInfo":{"name":"Seth", "title":"Seth Test Client", "version":"1.0.0"}
      }
    }'
    )
    ```

    ```shell
    curl -v localhost:8080 \
      -H "Accept: application/json,text/event-stream" \
      -H "Mcp-Protocol-Version: 2025-06-18" \
      -H "Mcp-Session-Id: ${SESSION_ID}" \
      -d '{
      "jsonrpc":"2.0",
      "method":"notifications/initialized"
    }'
    ```

    ```shell
    curl -v localhost:8080 \
      -H 'Accept: application/json,text/event-stream' \
      -H "Mcp-Protocol-Version: 2025-06-18" \
      -H "Mcp-Session-Id: ${SESSION_ID}" \
      -d '{
      "jsonrpc":"2.0",
      "id":1,
      "method":"tools/list",
      "params":{}
    }'
    ```

9. Get a response:

    ```text
    event: message
    id: 3_0
    data: {"jsonrpc":"2.0","id":1,"result":{"tools":[{"description":"Say hello","inputSchema":{"type":["null","object"],"additionalProperties":{"not":{}}},"name":"greet","outputSchema":{"type":"object","additionalProperties":{"not":{}}}}]}}
    ```

**Expected behavior**
I expect pointer types to be permitted. Unfortunately the response from the pointer-types is invalid and not recognized by Gemini CLI or Claude Code Desktop (I did not try other clients, but I expect it's the same). Diff from the resposnes:

```js
// concrete type
{
  "jsonrpc": "2.0",
  "id": 1,
  "result": {
    "tools": [
      {
        "description": "Say hello",
        "inputSchema": {
          "type": "object",
          "additionalProperties": {
            "not": {}
          }
        },
        "name": "greet",
        "outputSchema": {
          "type": "object",
          "additionalProperties": {
            "not": {}
          }
        }
      }
    ]
  }
}
```

```js
// pointer
{
  "jsonrpc": "2.0",
  "id": 1,
  "result": {
    "tools": [
      {
        "description": "Say hello",
        "inputSchema": {
          "type": [
            "null",
            "object"
          ],
          "additionalProperties": {
            "not": {}
          }
        },
        "name": "greet",
        "outputSchema": {
          "type": "object",
          "additionalProperties": {
            "not": {}
          }
        }
      }
    ]
  }
}
```

**Logs**
N/A

**Additional context**
N/A

### LINKED ISSUE #200: No tools are advertised when assigning a pointer type in the generic for `CallToolResultFor`
**Describe the bug**
When the generic type for `CallToolResultFor` is a pointer in the `ToolHandlerFor`, the tool is not included in clients.

Image

This is likely due to the response schema for `tools/list` being invalid.

**To Reproduce**

Prove that tools are included in the response with non-pointer types:

1. Create a small server:

    ```go
    package main
    
    import (
    	"context"
    	"net/http"
    
    	"github.com/modelcontextprotocol/go-sdk/mcp"
    )
    
    func main() {
    	server := mcp.NewServer(&mcp.Implementation{Name: "hello"}, nil)
    
    	mcp.AddTool(server, &mcp.Tool{
    		Name:        "greet",
    		Description: "Say hello",
    	}, func(ctx context.Context, ss *mcp.ServerSession, params *mcp.CallToolParamsFor[struct{}]) (*mcp.CallToolResultFor[struct{}], error) {
    		return &mcp.CallToolResultFor[struct{}]{
    			Content: []mcp.Content{
    				&mcp.TextContent{Text: "hello"},
    			},
    		}, nil
    	})
    
    	http.ListenAndServe(":8080", mcp.NewStreamableHTTPHandler(func(*http.Request) *mcp.Server {
    		return server
    	}, nil))
    }
    ```

2. Start the server:

    ```shell
    go run main.go
    ```

3. List the tools:

    ```shell
    SESSION_ID=$(curl -sfo /dev/null -w '%header{mcp-session-id}' localhost:8080 \
      -H 'Accept: application/json,text/event-stream' \
      -H 'Mcp-Protocol-Version: 2025-06-18' \
      -d '{
      "jsonrpc":"2.0",
      "id":1,
      "method":"initialize",
      "params":{
        "protocolVersion":"2025-06-18",
        "capabilities":{},
        "clientInfo":{"name":"Seth", "title":"Seth Test Client", "version":"1.0.0"}
      }
    }'
    )
    ```

    ```shell
    curl -v localhost:8080 \
      -H "Accept: application/json,text/event-stream" \
      -H "Mcp-Protocol-Version: 2025-06-18" \
      -H "Mcp-Session-Id: ${SESSION_ID}" \
      -d '{
      "jsonrpc":"2.0",
      "method":"notifications/initialized"
    }'
    ```

    ```shell
    curl -v localhost:8080 \
      -H 'Accept: application/json,text/event-stream' \
      -H "Mcp-Protocol-Version: 2025-06-18" \
      -H "Mcp-Session-Id: ${SESSION_ID}" \
      -d '{
      "jsonrpc":"2.0",
      "id":1,
      "method":"tools/list",
      "params":{}
    }'
    ```

4. Get a response:

    ```text
    event: message
    id: 3_0
    data: {"jsonrpc":"2.0","id":1,"result":{"tools":[{"description":"Say hello","inputSchema":{"type":"object","additionalProperties":{"not":{}}},"name":"greet","outputSchema":{"type":"object","additionalProperties":{"not":{}}}}]}}
    ```

5. Stop the server

6. Alter the code to use a pointer in `mcp.CallToolResultFor`:

    ```diff
    -	}, func(ctx context.Context, ss *mcp.ServerSession, params *mcp.CallToolParamsFor[struct{}]) (*mcp.CallToolResultFor[struct{}], error) {
    +	}, func(ctx context.Context, ss *mcp.ServerSession, params *mcp.CallToolParamsFor[struct{}]) (*mcp.CallToolResultFor[*struct{}], error) {
    ```

7. Start the server:

    ```shell
    go run main.go
    ```

8. Run the same commands from step 3 above:

    ```shell
    SESSION_ID=$(curl -sfo /dev/null -w '%header{mcp-session-id}' localhost:8080 \
      -H 'Accept: application/json,text/event-stream' \
      -H 'Mcp-Protocol-Version: 2025-06-18' \
      -d '{
      "jsonrpc":"2.0",
      "id":1,
      "method":"initialize",
      "params":{
        "protocolVersion":"2025-06-18",
        "capabilities":{},
        "clientInfo":{"name":"Seth", "title":"Seth Test Client", "version":"1.0.0"}
      }
    }'
    )
    ```

    ```shell
    curl -v localhost:8080 \
      -H "Accept: application/json,text/event-stream" \
      -H "Mcp-Protocol-Version: 2025-06-18" \
      -H "Mcp-Session-Id: ${SESSION_ID}" \
      -d '{
      "jsonrpc":"2.0",
      "method":"notifications/initialized"
    }'
    ```

    ```shell
    curl -v localhost:8080 \
      -H 'Accept: application/json,text/event-stream' \
      -H "Mcp-Protocol-Version: 2025-06-18" \
      -H "Mcp-Session-Id: ${SESSION_ID}" \
      -d '{
      "jsonrpc":"2.0",
      "id":1,
      "method":"tools/list",
      "params":{}
    }'
    ```

9. Get a response:

    ```text
    event: message
    id: 3_0
    data: {"jsonrpc":"2.0","id":1,"result":{"tools":[{"description":"Say hello","inputSchema":{"type":"object","additionalProperties":{"not":{}}},"name":"greet","outputSchema":{"type":["null","object"],"additionalProperties":{"not":{}}}}]}}
    ```

**Expected behavior**
I expect pointer types to be permitted. Unfortunately the response from the pointer-types is invalid and not recognized by Gemini CLI or Claude Code Desktop (I did not try other clients, but I expect it's the same). Diff from the resposnes:

```js
// concrete type
{
  "jsonrpc": "2.0",
  "id": 1,
  "result": {
    "tools": [
      {
        "description": "Say hello",
        "inputSchema": {
          "type": "object",
          "additionalProperties": {
            "not": {}
          }
        },
        "name": "greet",
        "outputSchema": {
          "type": "object",
          "additionalProperties": {
            "not": {}
          }
        }
      }
    ]
  }
}
```

```js
// pointer
{
  "jsonrpc": "2.0",
  "id": 1,
  "result": {
    "tools": [
      {
        "description": "Say hello",
        "inputSchema": {
          "type": "object",
          "additionalProperties": {
            "not": {}
          }
        },
        "name": "greet",
        "outputSchema": {
          "type": [
            "null",
            "object"
          ],
          "additionalProperties": {
            "not": {}
          }
        }
      }
    ]
  }
}
```

**Logs**
N/A

**Additional context**
- Similar to https://github.com/modelcontextprotocol/go-sdk/issues/199

### PR DESCRIPTION
**Pull request by findleyr**
As reported in #199 and #200, the fact that we return a possibly "null" schema for pointer types breaks various clients, which expect schemas to be of type "object". This is an unfortunate footgun. For now, assume that the user wants us to treat pointers equivalently to non-pointers. If we want to change this behavior in the future, we can do so behind an option.

+ a test

Also fix the handling of nil results in the case where the output schema is non-nil: we must provide structured content in this case. (This was causing the test to fail).

Fixes #199
Fixes #200

### CODE REVIEW

**Comment by jba** [comment]
This is thorough. But it won't merge at all after #325. I gutted newServerTool.
I'll wait for your rebase before reviewing. You may want to reintroduce setSchema, now that there is more logic to it.
Originally I was going to add an option to jsonschema.ForOptions for this, but your way is better.

File: mcp/server.go [hunk 1]
```diff
@@ -255,12 +250,54 @@ func toolForErr[In, Out any](t *Tool, h ToolHandlerFor[In, Out]) (*Tool, ToolHan
 			res = &CallToolResult{}
 		}
 		res.StructuredContent = out
+		if zero != nil {
+			// Avoid typed nil, which will serialize as JSON null.
+			// Instead, use the zero value of the non-zero
+			var z Out
+			if any(out) == any(z) { // bypass comparable check: pointers are comparable
```
Comment (jba) [inline mcp/server.go]: Won't this panic if Out = []int, for example?

**Review by jba — CHANGES_REQUESTED** [review]

File: mcp/server.go (hunk 1 above)
Comment (findleyr) [reply mcp/server.go]: No, zero is only non-nil if Out is a pointer type.

File: mcp/mcp_test.go [hunk 2]
```diff
@@ -1084,3 +1084,104 @@ func TestNoDistributedDeadlock(t *testing.T) {
 }
 
 var testImpl = &Implementation{Name: "test", Version: "v1.0.0"}
+
+// This test checks that when we use pointer types for tools, we get the same
+// schema as when using the non-pointer types. It is too much of a footgun for
+// there to be a difference (see #199 and #200).
+//
+// If anyone asks, we can add an option that controls how pointers are treated.
```
Comment (jba) [inline mcp/mcp_test.go:1092]: Actually, we can't: AddTool doesn't take options.
Should we add them?

Comment (findleyr) [reply mcp/mcp_test.go:1092]: No, definitely not. We can add a jsonschema.ForOption.

File: mcp/server.go (hunk 1 above)
Comment (findleyr) [reply mcp/server.go]: Tried to make this clearer in comments.

**Review by jba — APPROVED** [review]
