### PR TITLE
mcp: simplify ServerSession.initialize

### LINKED ISSUE #222: Simplify ServerSession.initialize
Lock for the entire method: it doesn't do anything that takes a long time. Remove the initialized field and use the presence of the initialized parameters instead.

### LINKED ISSUE #225: mcp lifecycle: initialization phase is not completely followed
**Issue**

- MCP server is responding to `tools/list` request, even before receiving `initialized` message. 
- As per the MCP specification
>The server SHOULD NOT send requests other than [pings](https://modelcontextprotocol.io/specification/2025-06-18/basic/utilities/ping) and [logging](https://modelcontextprotocol.io/specification/2025-06-18/server/utilities/logging) before receiving the initialized notification.

**To Reproduce**
1. Start MCP server
2. Send `initialize` message from client to server
3. Send `tools/list` message from client to server

**Expected behavior**
The `tools/list` call should result in error citing initialization phase is not fully complete

**Logs**
```
$ go run github.com/modelcontextprotocol/go-sdk/examples/hello
{"jsonrpc":"2.0","id":1,"method":"initialize","params":{"protocolVersion":"2024-11-05","capabilities":{"roots":{"listChanged":true},"sampling":{},"elicitation":{}},"clientInfo":{"name":"ExampleClient","title":"Example Client Display Name","version":"1.0.0"}}}
read: {"jsonrpc":"2.0","id":1,"method":"initialize","params":{"protocolVersion":"2024-11-05","capabilities":{"roots":{"listChanged":true},"sampling":{},"elicitation":{}},"clientInfo":{"name":"ExampleClient","title":"Example Client Display Name","version":"1.0.0"}}}
{"jsonrpc":"2.0","id":1,"result":{"capabilities":{"completions":{},"logging":{},"prompts":{"listChanged":true},"resources":{"listChanged":true},"tools":{"listChanged":true}},"protocolVersion":"2024-11-05","serverInfo":{"name":"greeter","version":""}}}
write: {"jsonrpc":"2.0","id":1,"result":{"capabilities":{"completions":{},"logging":{},"prompts":{"listChanged":true},"resources":{"listChanged":true},"tools":{"listChanged":true}},"protocolVersion":"2024-11-05","serverInfo":{"name":"greeter","version":""}}}
{"jsonrpc":"2.0","id":2,"method":"tools/list"}
read: {"jsonrpc":"2.0","id":2,"method":"tools/list"}
{"jsonrpc":"2.0","id":2,"result":{"tools":[{"description":"say hi","inputSchema":{"type":"object","required":["name"],"properties":{"name":{"type":"string","description":"the name to say hi to"}},"additionalProperties":{"not":{}}},"name":"greet","outputSchema":{"type":"object","additionalProperties":{"not":{}}}}]}}
write: {"jsonrpc":"2.0","id":2,"result":{"tools":[{"description":"say hi","inputSchema":{"type":"object","required":["name"],"properties":{"name":{"type":"string","description":"the name to say hi to"}},"additionalProperties":{"not":{}}},"name":"greet","outputSchema":{"type":"object","additionalProperties":{"not":{}}}}]}}
```

### PR DESCRIPTION
**Pull request by findleyr**
First, make the simplifications described in #222. I don't know why we originally had such fine granularity of locking: perhaps we were going to execute 'oninitialized' callbacks.

Then actually fix the 'initialized' condition, by not setting the session as initialized until 'notifications/initialized' is actually received

Fixes #222
Fixes #225

### CODE REVIEW

File: mcp/server.go [hunk 1]
```diff
@@ -753,19 +753,16 @@ func (ss *ServerSession) initialize(ctx context.Context, params *InitializeParam
...
-		ss.mu.Lock()
-		ss.initialized = true
-		ss.mu.Unlock()
-	}()
+	// TODO(#26): Technically, the server should not be considered initialized
+	// until it has *responded*, but since jsonrpc2 is currently serialized we
+	// can mark the session as initialized here. If we ever implement a
+	// concurrency model (#26), we need to guarantee that initialize is not
+	// handled concurrently to other requests.
+	ss.initialized = true
```
Comment (jba) [inline mcp/server.go]: Can't you drop the boolean and test if initializeParams != nil?

Comment (findleyr) [reply mcp/server.go]: No, because we're doing this wrong: https://github.com/modelcontextprotocol/go-sdk/issues/225.

I'm fixing that in a separate CL.

**Comment by findleyr** [comment]
PTAL, I included a second CL to actually fix the initialization condition.

**Comment by jba** [comment]
So _initialized catches double initialization.
Does that need to be included in SessionState? I think so.
